### ISSUE TITLE
FW: ConcurrentModificationException in Client.java

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-java-legacy#166]
@PrabithaK reported an [issue in the JS-Helper ](https://github.com/algolia/algoliasearch-helper-js/issues/454) but it doesn't look like an issue from the JS Helper. Maybe more luck here :)

**Comment by ElPicador** [comment]
@PrabithaK could you please provide us with the fullstacktrace you have?

**Comment by ghost** [comment]
Hi @ElPicador, 

Please find the stacktrace:

Caused by java.util.ConcurrentModificationException
java.util.ArrayList$ArrayListIterator.next (ArrayList.java:573)
com.algolia.search.saas.Client.multipleQueries (Client.java:362)
com.algolia.search.saas.Client$5.run (Client.java:270)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.doInBackground (AbstractClient.java:692)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.doInBackground (AbstractClient.java:688)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.lang.Thread.run (Thread.java:818)

Thanks,
Prabitha

**Comment by ElPicador** [comment]
Thanks @PrabithaK

The class `Client.java` doesn't exists. Which version of the API Client are you using?

**Comment by ghost** [comment]
It was 3.+ in gradle.

**Comment by bobylito** [comment]
@PrabithaK Are you building an android app? cc. @PLNech

**Comment by ghost** [comment]
Yes we are using algolia in our search process in Android App. This crash occurs randomly. And couldn't identify whether it is not properly handled at the app end. 

P.S. Now I have changed the version to 3.5 as mentioned in algolia documentation for android.

**Comment by bobylito** [comment]
@PrabithaK I forward this issue to the wrong repo sorry 🙇 I will move it to [the android repo](https://github.com/algolia/algoliasearch-client-android/issues/230).
